In [1]:
import pandas as pd

In [23]:
messages = pd.read_csv(r"smsdata\SMSSpamCollection.txt", 
                      sep = "\t", 
                      names= ["label", "message"] )

In [24]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Data Cleaning & Text Preprocessing

In [18]:
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [25]:
ps = PorterStemmer()
corpus = []

for i in range(0, len(message)):
    # We need textual data only
    review = re.sub('[a-zA-Z]', " ", messages['message'][i])
    
    # convert entire data into lower-case
    review = review.lower()
    
    # SPlit our entire data
    review = review.split()
    
    # remove the stop words
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    
    review = " ".join(review)
    corpus.append(review)

In [26]:
corpus

[', .. ... ...',
 '... ...',
 "2 21 2005. 87121 ( ) & ' 08452810075 18'",
 '... ...',
 "' ,",
 "' 3 ' ! ' ? ! , £1.50",
 '. .',
 "' ( )' . *9",
 '!! £900 ! 09061701461. 341. 12 .',
 '11 ? ! 08002986030',
 "' ' , ? ' .",
 '! 100 20,000 > 11 87575. 150 / , 6 , 16+ 4',
 '! 1 £100,000 ! : : 81010 & . . 4403 1 7 18',
 "' . . .",
 '!!',
 ': , >> :// . . ? =',
 "... ' :)",
 '2 ... . .',
 '\x92 . \x92',
 '- / . 87077 87077 : , 4 /ú1.20 36504 45 16+',
 '?',
 '‘ 2',
 'ü ... ...',
 '. 3 . ?',
 '. ?',
 ". ' . . . ' .",
 '.',
 "? ? ? ' ? ?",
 "' & ; ' , ' '",
 '. . ! ?',
 "' , ' '",
 "2 . . 2! ' ! . ?",
 '.',
 '?',
 '£5/ .',
 '... ü ... 2 8',
 ", ' '",
 '',
 '... ...',
 "! ' ? ' . ' !",
 '. . .',
 '? , , ... ... ... ...',
 '07732584351 - - = + . 08000930705',
 '?',
 '! . & ;#& ; ...',
 '.. ..',
 "' .",
 ', ?',
 ", '",
 "' . ' . ' . .",
 '. .',
 '& ;#& ; , & ;#& ;',
 "'",
 '. . , " ". \' \' \' . \' . \' .',
 '. : . ? ?',
 '? @ & ; & ;',
 '! 1 2 . 09061209465 ! , 3, 3, 4 ! 420- 4-5 . 150 . !',
 ", ' .",
 '',
 '.. .',
 "$1 . ' . .",
 '. .',
 '',
 ', ?',
 '. .',
 ', . £1500 , 09066364589',
 '" .." ? ...',
 ', & 41 £1000. 87121 18+6*£1.50( . )10, 1 3',
 '" "? \' !',
 '.',
 '... ... ...',
 '.',
 '?',
 '.. :) ? ?',
 '...',
 '. .',
 '. .',
 ':) .',
 '& ;#& ;',
 ". . ' .",
 ", '",
 '. ?',
 '',
 '',
 '.',
 ", ' . , .",
 "? 2 ' . .",
 "' . . .",
 "'",
 '., , ..',
 '! ‘ - ‘ !',
 ". ? ' 42 . .",
 '1 !!',
 '0800 169 6031 10 -9 £1000 £5000 !',
 '. 530 . ?',
 '. " " 85069 . . , 5249, 17 92 . 450 16',
 '.. ?',
 '.',
 '. - ! . . ?"',
 '',
 "' . .",
 '! ?',
 "' . 4 .",
 "' ( )' . *9",
 ". ' ! ' . , . .",
 '',
 '. .',
 ", '",
 "'",
 '! . . ...',
 ". ' .",
 '?',
 '. .',
 "' 2 . . .",
 '! . £1000 . 09064012160. 52. 12 . 150',
 ", ... , ' , ' ... ... ?",
 ", '' ' !!''. . 4 . . .",
 '2 £1000 4* ( ) 2 0871277810910 / (18+)',
 '! - - !',
 "... ' . .",
 '! 2004 07742676969 786 . 08719180248 : 45239',
 '! . £2000 5/9/03 ! 09064019788 42 29 , 150',
 '- & &',
 '7548 $350 . 08712300220 4041',
 '. 12',
 "ü ü' ?",
 ', .',
 ", ' . . , . ' , .",
 '.',
 '. ? ! !',
 '.. :) ?',
 "' .",
 ', . .',
 '.',
 '! ? 82277. £1.50 :',
 "2 ? 2 ? ' 69888! . 2 . 31 . @150",
 ". ' @ .",
 '.',
 '.',
 "' . : 69988 &",
 '... ... ü ... ...',
 ", '",
 ', .',
 ': " 4 .." .. .. 8',
 '. ?',
 '',
 '?',
 "' ? ' , , . . 08700621170150",
 '. . .',
 '.. ?',
 '..',
 "' ..",
 '2 2 .',
 '... ...',
 "' ( )' . *9",
 ', , , . , . , . , . . , , , , .',
 '?',
 "' ...",
 ', . ? ? ? ? ? ?',
 '. . 07046744435',
 '2 £1000 4* ( ) 2 0871277810810',
 "'",
 '.:) :)',
 "' . ' . .",
 '- (32/ ) . -434 -434 : . . / / ? 62468',
 '. 2 . , . . /',
 '.',
 '! . £900 . 09061701939. 89. 12',
 ", ' ?",
 '. .',
 ':) :) .',
 ', .',
 '.. ... , 4 ... ...',
 '?',
 ', . , ...',
 ", ' . ... .",
 "'",
 '?',
 "' ~ & ;#& ; , $ & ;#& ;",
 '.',
 "! . ' . .",
 '. . . 8',
 '. .',
 '. .',
 ', ?',
 '.',
 "! ? ? ? ' ? ?",
 ',',
 '0808 145 4742 9 -11 £1000 £5000 !',
 '.',
 '. . ...',
 '? 30 . . . .',
 "' . ' . . . .|",
 ':) :)',
 '. .',
 "? ' . 8",
 '',
 '',
 '? 1 ?',
 '? ! . :)',
 ', & ;#& ; , ?',
 '& ;#& ;',
 '',
 '& ; & ; . & ; & ; . & ;#& ; .',
 '.',
 '11 .',
 'ü ...',
 ", '' ' !!''. . 4 . . .",
 ',',
 '& ; & ;',
 ':) !',
 "' , . .",
 '',
 ':) :) :) .',
 '... ü ...',
 '! ?',
 '.',
 ". ' .",
 '? ..',
 '3',
 ". . ' . .",
 '. .',
 '... ..',
 ", '",
 '... . . .',
 '500 2004, ! : : 89545 & ! £1 .4- . 2 087187262701.50 / 18',
 '. .',
 '? 2 ? 2 , , . .',
 '.',
 '... & ; , & ; . . . .',
 '',
 '. & ;#& ; .',
 '',
 ", '",
 ':) ..',
 '& . . 4 10 . & 25. 18 - @',
 '. & ;#& ;',
 '',
 '? ?',
 ": , . .. . . . & ; , ' .!",
 '447801259231 2 - * - 09058094597',
 '.',
 '',
 '. , . , .',
 "' ' . 4 ' , ' ...",
 "' ?",
 ". . '",
 '',
 '2 .',
 '. . . . .',
 '500 125 & 2 100 87066 . . 1 150 3 16',
 '5',
 ', .. , !.. ... .',
 '? ?',
 '3 , 2 . .',
 "' , '",
 "' '",
 '...',
 '? ...',
 '? 750 ? ? ? 08000930705',
 '‘ !!!! ?',
 '',
 "' . . .",
 '. 0125698789 ! *',
 '69698 150 69698',
 '.',
 '.',
 ',',
 '! 25 ! 4 . ! ? 87070. 150 / 4 1146 45 2',
 '. . ?',
 ': ! .',
 ", '",
 ', . .',
 '500 . 4 . ! 86688 : .100 - .',
 ', 1',
 '. .',
 '...',
 '',
 ", '",
 '. ?',
 '? ? ?',
 '?',
 ', ..... , , - - ..',
 '.',
 '...',
 "' , '",
 ',',
 '..',
 '2?',
 ', , , , :-).. :-)..',
 ', . , . . . .',
 '?',
 '? .',
 '. 4 .',
 '',
 '. .',
 "- & & . 0845 021 3680. 28 . & '",
 "'",
 '... ... ... ..',
 '.',
 "? ' '",
 ', :',
 ', . . , ?',
 '! ?',
 '',
 '. 4 !: 1 21/ , . :// . . / / 3 8 7!-4',
 '... ... ...',
 '?',
 ". ' .",
 '> , , , , , 82468',
 "? '",
 '.. ? 1 1 1',
 '? £200 , 85222 ! & 84, 26 3 . 16+. 1.50/',
 "' ' '",
 '2 , & . & 4 . .',
 '. .',
 '. :) .',
 '... 4 ... , ... , ...',
 ", ' :(",
 '! 11 +? ! 08002986906',
 ', ...',
 ', * *',
 '... ...',
 '8 2 & 4 1.',
 ". ' . - . !",
 '. ?',
 '.. ..',
 ':) ?',
 "' ' , ,",
 ", '",
 "' . .",
 '. :) . .',
 '..? .',
 '1 ! 0844 861 85 85. . !',
 "' . . .",
 '! £1000 ! 83600 . 150 / . :08718720201.',
 '- ! , ?',
 '. ?',
 '..',
 ", '",
 '? ...',
 "' .",
 '! 1000 ! . .',
 '?',
 '.',
 '.',
 '.... ...',
 '. . . .',
 '.',
 '? . ? . 69876. 1.50 . .',
 '. .',
 "' , '",
 "' '",
 ".! , ? , , '",
 '?',
 '& ;#& ; 5 . .',
 '. . . . , , .',
 '500 125 & 2 100 87066 . . 1 150 3 16',
 '- 500 - - 86688 150 / . : 08708800282 / 342/2 / 1 6',
 "' . , . ' , . ' , .",
 '! , - ! .',
 ':-):- -)',
 '..',
 "'",
 '. . ...',
 '! ? ? ? , ...',
 '. .',
 '_ - ! , & & ! & 1000 . 8 08000839402 2 / 4 =',
 '176781. . . . . . 08717205546',
 '? ?',
 ", '",
 '... . , . ...',
 ':)',
 "' & ;#& ; ..",
 '.',
 ', 91. 4 . 09057039994',
 '',
 ".. ' .:)",
 "' * *",
 '',
 '. . . ..',
 "' . ' . ' ' . ' . , . ' . .",
 ',',
 '. :-) .',
 '... 945+',
 '4 6 . , . 8 08000839402 2 / 9',
 '3',
 '.',
 '',
 '4 & 4 . 11 ? 08000938767 ! 2',
 '.. ?',
 '... ?',
 '? ?',
 '.',
 '. .',
 '7.30 ? ?',
 '. ..',
 '. 8. . .',
 ". . ' . , .",
 ', . . , , . . , . , .',
 '... ... :-) ..',
 '87131 87131 ! ? 0845 2814032 16 1 , 3 £150 £',
 '.',
 '.',
 "'",
 ', & ;#& ;',
 ',',
 "! . ' . + ?",
 '! ? ?',
 '',
 ': * : * * * : * .',
 '',
 '',
 "... ' ... , , ...",
 '=',
 '100 ; 09064012103 334 38',
 '.',
 '',
 '£250 80086 . 18 & . . .',
 ", ' ,",
 '2 - 2 . 1 2 07123456789 87077 ! 36504 45 4 150',
 ":) ' .",
 '! 09111032124 . 12 146 150',
 ':-.',
 '! £2000 . 09058094455 . 3030. 12',
 '..... ? 1. 2. 3. 4. 5. 6. 7. 8. 9. & ;#& ; . & ;#& ; . . ..',
 ". ' .",
 '.. ..',
 '?',
 '7 .. ü ..',
 '.. . & ;#& ; . . & ;#& ; ..',
 '.',
 '',
 '! 3650 09066382422 150 3 16+ 300603 4284 1 3',
 '?',
 "? ' & ; & ;#& ;",
 '& ;#& ; . & ;#& ; & ;#& ; ?',
 ", '",
 '',
 '~ , 50 .',
 '. .',
 '.. .. :). .',
 '& ;:(',
 '... ... ...',
 ", '",
 '! , ? ?',
 ", , ' , ' ?",
 ', , , , , .',
 ':-)',
 '... ?',
 '10 ...',
 '!',
 '',
 ':) :) ? ?',
 '. .',
 "£500 - £75,000. + . ? . 0800 1956669 ' '",
 '. .',
 ', . \x92 \x92 .',
 "' . .",
 '1.20 . . , , ,',
 '. . .',
 '?',
 '. .',
 ", . 0207 153 9153. 26 . & ' . -",
 ", '",
 '',
 '! . . ? & ;#& ; :)',
 "' ?",
 '?',
 ", . ' 4 2 .",
 '. .',
 ': 4* #5000 ! 09061743806 . 326 25 150',
 ', ?',
 '. , . & ;#& ; & ;#& ; . . 9 ...',
 "2 ? 2 ? ' 69888 . 2 . 31 . @150",
 "- ' 1 ... ... 9 :)",
 "'",
 '.. ..',
 '? ? ?',
 ", 8 ' ?",
 "' ?",
 ',',
 ', , ?',
 '...',
 '! ...',
 '',
 '1 .',
 '500 & , .07781482378.',
 '.',
 '. , , 6. 2',
 "' ?",
 "' ,",
 '! 1 2 . 09061209465 ! , 3, 3, 4 ! 420- 4-5 . 150 . !',
 ", '",
 '& ;#& ; ?',
 '? ?',
 '... ?',
 '... ...',
 '. .',
 '7 , ?',
 '',
 ', 1 - - .',
 'ü ?',
 '.',
 '. .. .?',
 "+123 - ' £1450 09050002311 4280703. & / 08718727868. 18 150",
 "' ' . 2 . .",
 ', ?',
 ". ' . . ' . . ....|",
 "' ?",
 '? 1. 2. 3. 4. 5. 6. 7. 8. 9. ..',
 "8 , '",
 ".. ' .. .. '",
 ':)',
 '.. ..',
 ', 40 3 £500 ! : : 83355! 15 150 / 18+',
 ':) .',
 '150 # # 3 1. 2. 3. 6. 8. 4',
 ':// . .',
 '. , , . .',
 "' . .",
 "' .",
 '',
 '',
 "' , ?",
 '!: . £2,000 02/09/03! 2 ! 0871-872-9755 95',
 "' 4 . ' .",
 "' ! £150 ! 85023 ! , ! 08717898035. £3.00 . 16 .",
 '! ?',
 '24 . 750',
 "' -",
 '! 2003 07815296484 800 - . . . . 08718738001 41782 18/11/04',
 '- .. .. ..',
 '.... ...',
 "' ...",
 "' . 8 . , . .",
 ', ! ? . ,',
 ', & ;)',
 "' .",
 '..',
 ', .',
 '. . @50 / 6/ & 16 2',
 ": ' ' , ......... ' '",
 '. . . .',
 '4 . .',
 ". ' .",
 '?',
 ". . '",
 ',',
 '& ;#& ; ..',
 "5 . ' . .",
 ', ... , ... ,',
 ", ' -",
 ", '",
 ". ' . .",
 '‘ ‘ . ‘ ‘',
 '. .',
 ':) ? ?',
 '.',
 '! . . ?',
 '... ... , ... ... , ... ..',
 ":) ' ..",
 "4 ' ...",
 '...',
 '! . £1000 . 09064012160. 52. 12 . 150',
 "... , ? ' ? ... ... ...",
 '2 , 2 ?',
 '? ?',
 ', , * * ...',
 '! ! !',
 '?',
 '4 2 ... ... ...',
 '',
 '?',
 '.',
 '4 ...',
 '?1,000 ?2,000 ! , 09050000327',
 "' . , ' .",
 'ü 4 5..',
 '£5000, 09050005321.',
 '. & ; , .',
 '.. ü ?',
 '',
 '750 150 08002988890',
 '- . ?',
 "' . . .",
 '1 .',
 "' ... , ? ... ...",
 '',
 '',
 "' ,",
 "£250 : 80878. ' & ' . -2- . 08715705022, 1 150 /",
 '2000 ! 08712402050 . 10 . 16+. & .',
 '! 2003 07753741225 800 - . . . . 08715203677 : 42478 24/10/04',
 '?',
 '. , . !!! ...',
 '! ?',
 '',
 '. 0800 542 0825 !',
 '. . .',
 "' ' .",
 '.. .. ..:-',
 "' . ' .",
 '?',
 '.',
 '...',
 '',
 '@ 2 28/5 . 2 !!! : 07946746291/07880867867',
 '',
 "' ..",
 "' , . ?",
 '22 ! 2004 . 83222',
 '. . . . .. 5 . - ?',
 '',
 '4 2 2 .',
 ':) .',
 '. 1 ...',
 '. . . .',
 '..',
 'ü ... ...',
 '. . .',
 '& ;#& ;',
 '.... .',
 "'",
 ', , . .',
 "' , '",
 ", ' 8",
 '?',
 '. 2 .',
 '2 4 25 2 . . 89693',
 '4882 £350 . 09064019014 £350 .',
 '.',
 '!',
 '.',
 '. – .',
 ', 2 , :// . - . . / & .2 80062.',
 '...',
 ', ! .',
 'ü ... ü ?',
 ', ?',
 '.',
 ", ' '",
 ", , ' ! ' ! !",
 '',
 '. . .',
 '! . ‘ ‘ .',
 ', & ; & ; .. ?',
 '? .',
 '! 2003 800 - . . . . 08715203694 : 40533 31/10/04',
 '. .',
 '?1,000 ?2,000 ! , 09050000327. & : , 7 3 . 150',
 '! . :)',
 "' . . . ! ?",
 ', ? !',
 '.',
 '',
 "'",
 '. . , .',
 '',
 '. , .',
 '88800 89034 08718711108',
 ", . , . , . , 3 ... '",
 "' ?",
 '... ü ...',
 ':-). :-)..',
 '! ;)',
 '.. / ?',
 "'",
 '& ; & ; :)',
 '!',
 '?',
 '- !',
 '. 0819 :" , . !!!" ? 62468',
 '1 ! . 8 20 £1.50 2 08452810071 16',
 ". ' . , ' . .",
 "' & ;#& ; , ?",
 ', ..',
 '?! . ?',
 ", ? ' . ' 4 ...",
 "'",
 ". . ' . ' .",
 "' ' ? !",
 "ü 4 . ' 8",
 '4 ?',
 "' . 20 . . - ' . 89555. 2 1 150 18+",
 'ü 4 . .',
 '? :)',
 '.. , . 8',
 ', . . . . .',
 '. .',
 '< 448712404000> 08712404000 .',
 '?',
 '. 4 ? 1405, 1680, 1843. 2 1 , . .',
 ', . .',
 '. ?',
 '.',
 '. .',
 ", ' ?",
 '… !',
 'ü ...',
 '.. ..',
 'ü ?',
 ", '",
 '',
 ', ?- ? , !',
 ".. . ' ...",
 "' ,",
 '',
 '... 12 ...',
 '- , 2 . . / .',
 '4 & 4 . 11 +? 08000938767 ! 2 &',
 ': & ; 2 . . .. 1 ... :" , ........ ..',
 '',
 '08714712388 10 -7 10',
 '. , .',
 '. .',
 '.',
 '+449071512431 ! 2 ! £1250 09071512433 4 050703 & 4235 1 3 . 150 . £7. 50',
 "? ... ... ' . 3748",
 '£1000 £2000 . 08714712394 10 -7',
 '. . . .',
 '?',
 "' . . .",
 '.',
 '',
 '. , . , . ? . , . .',
 '! ... !',
 "' ... 1 ... ... ...",
 ', 8',
 '. .',
 '.',
 ': : 2 : - 123',
 "' . !",
 "' =",
 '.. ..',
 '. . .',
 '',
 '. .',
 '. : 6650 £10 ! : : 81151 & ! 4 & 150 /',
 '!',
 "' ... . . .",
 '. .',
 ':) . :',
 ". . …. ' 8 7. . .",
 '. .',
 '. .',
 '. 930.',
 ', . . . !',
 '£3 10 82324. 08706091795',
 "' ?",
 '.',
 "40 , ' ?",
 '.',
 '',
 '',
 "- ' :) ?!",
 '?',
 '* *',
 ', , , ! !',
 '',
 "/ / , '",
 '. 2 , 2 £79 4 . 08704439680 & .',
 '. , ? ! . .',
 '£500 ! 09066368327 04/09/02 39 51 £1.50 2 - 734 27',
 '... ... ... ...',
 '" " ..',
 '£200 . 88039 . . 087147403231 ! 16 £1.50',
 "' , , 4 ... , ...",
 ", '",
 '.',
 "! ' . . ' .",
 '!',
 '! ! . 4 . ?',
 ',',
 '& ;#& ; .',
 '..',
 '.',
 "' '",
 '. !',
 '. . .',
 '',
 '? 1. 2. 3. 4. 5. 6. 7. 8. 9. ..',
 '... 2 , 3 ... ... ?',
 '?',
 '. 0800 542 0578 !',
 '. 5',
 "' , '",
 '. . .',
 '? . (100 / )',
 '5 087018728737, . , 81618, £3 . 08718727870.',
 '',
 ". ' . .",
 '4 :-)',
 '? ? \x92 !!!!!!!!!',
 '. ! !',
 "' . ' - . ?",
 "' .",
 ", . 0207 153 9996. 14 . & ' . -",
 '',
 '4 .',
 '& ;#& ;',
 '! £150 ! 85023 ! , ! 84, 263 . £3.00 . 16',
 "& ; & ; . ' .",
 '1 ! 1 4 8077 . . . . 36504 45 16+ 150 /',
 '£200 £1000 08000407165 (18+) 2 88222 . 21 4',
 "' 4.",
 '3',
 ", '",
 '. .',
 '',
 "' . ' .",
 ':) . & ;#& ; :)',
 "' . ' .",
 '£500 & 2 £100 87066 . . 1 150 3 16',
 '.',
 '5120 . 2 , . / 2 ,',
 "' ? ... ?",
 ", ' . '",
 '',
 '',
 '! ? 2 ! ? & \x92 2 .',
 "! ' ? ? ? * * * *",
 '',
 '. , . . = 3 9 , . 08702840625. . 220- 2 9',
 "25 4 ' . 8 . 8007 : 08701417012 2 .",
 '!',
 '.. ... * * ...',
 '..',
 '. ?',
 ', & ;#& ;',
 '. . .',
 '. . 09065174042. . 1.50 . 07821230901',
 '3 \x92 1 !',
 ', , :// . - . . / & . , 80062',
 ". , . . ' ! . !",
 ':)',
 '........... & ; .',
 '750 150 08002888812',
 ", $ & ;#& ; . ' . ' . .",
 '750 08000930705',
 '2 £150 - 85023 ! - 08717898035. £3.00 . 16 .',
 '\x92 2 2',
 "' , .",
 "' . .",
 '! 09066350750 . 4* 10,000 & 434 3 8 150 18+',
 '. :) ?',
 ": & ;#& ; ' . ' '",
 "' . .",
 ':) .. . :).',
 "' , . ,",
 "' ! £150 ! 85023 ! , ! 08717898035. £3.00 . 16 .",
 '? 2 ?',
 ', ! ...',
 '.',
 '! ! 2 .',
 ". ' ' ' .",
 '!! . 83110 .',
 '?',
 '. & ; & ; . .',
 '?',
 '',
 '. .',
 '',
 ", , ? '",
 '.',
 '',
 '09061104283 & . . £1.50 3',
 ", '",
 '! 2003 07808 800 - . . . . 08719899217 : 41685 07/11/04',
 '. . ? .',
 '? 100 & ? 0800 0721072 !',
 ', !',
 '... .. ...',
 "'",
 ". ' .",
 '...!!! ...!!! - - & ;#& ;',
 ', , 10 , 5 , £500 £100 , , 09064011000. 01327 150',
 '?',
 '! ? 82277. £1.50 :',
 '2 - * - 09058094565',
 '2 - * - 09065171142- -08',
 ': . :// . . / .',
 ", . ' , 2. . , , .",
 '. ... ?',
 '',
 '.',
 '.',
 '. .',
 ". ? . ' .",
 '',
 '.',
 '?',
 '! ? :)',
 '. . . . . . .',
 "' ' ' . 4 .",
 "' ' & ;#& ;",
 '- " . .":-)',
 '.',
 "' . ' ' . , .",
 "? , , '",
 '. " " 85069 . . , 5249, 17 92 . 450 16',
 '. .',
 '. .',
 '? ,',
 "' ...",
 "' ,",
 "' .",
 ', , , ! !! 82468',
 '. .',
 '',
 '! , 08709222922. 1.5 / 7.8 / ! 08712460324 (10 / )',
 "! ' ? .",
 '.',
 "' . . ' . ' . . ' :/",
 '. .',
 ', .',
 '',
 '.',
 ", ... , \\' ..!!",
 '? ?',
 '.',
 '',
 ". '",
 '. .',
 ".. ' ..",
 '.. . .',
 ', .. & ;#& ;',
 "' . 1 . ' .",
 ':) :)',
 '?',
 '!!! ! 2 2 88600 £1 ! 150 3+ 403 1 1',
 "' ' 2 . . ' :-)",
 '.',
 '',
 "' ?",
 '09063440451 , 4* £1000 . 150 & 334 38 .',
 '...',
 ', , , .',
 ':) . ?',
 '! 09061749602 . 4* £10,000 & 528 20 1 150 18+',
 '. . . .',
 "' . . ! :)",
 '. .',
 '? ! (150 / )',
 "'",
 '. , . ,',
 '! ? :)',
 '- 500 - - 86688 150 / . : 08718720201 114/14 / 1',
 '... ?',
 '',
 '?',
 ", '",
 '... ...',
 '.. : " .. .."',
 "'",
 '',
 "... ... 4 ... ' 2 ...",
 "' , ' . , , ,",
 '',
 ". . ' !",
 '@',
 "' ?",
 '! . £800 . 09050001808 . 95. 12',
 ', & ; & ; .. ?',
 '? ..',
 '',
 '& ;#& ; .',
 '. . .',
 '?. . . .. . . .',
 '.',
 '2.15 2 , ?',
 '2 , . . ?',
 ',',
 '.',
 '?',
 '...',
 '2 !',
 '',
 '. .',
 '. . & ;#& ; .',
 '. .',
 '. .',
 '* .',
 '! 2 3 . 09063458130 ! , , , .',
 '.',
 '',
 "' & ;#& ;",
 "' . & ;#& ; :)",
 "... , ? . , ' ... * *",
 '. ü . 67441233 . 8,22,65,61,66,382. , .6 1 5 .è',
 '. . .',
 '26',
 '! 7 ! ? 5 .',
 'ü... ü ... ...',
 '.. .. .. & ; ...',
 "' , ' !",
 "... ' ...",
 "' . .",
 '. . . . ?',
 'ü 4 . ü ü.',
 ...]

In [ ]:
# numerical data
#BAG of words, TFIDF, Word2vec and Doc2vec

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [49]:
cv = CountVectorizer()

In [31]:
X = cv.fit_transform(corpus).toarray()

In [32]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
y = pd.get_dummies(messages['label'])
y = y.iloc[:, 1].values

In [35]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

# Split data into train & test

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 0)

In [40]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Build ML Model

In [41]:
from sklearn.naive_bayes import MultinomialNB

In [42]:
spem_detect = MultinomialNB().fit(X_train,y_train )

In [43]:
spem_detect

MultinomialNB()

In [44]:
y_pred = spem_detect.predict(X_test)

In [45]:
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=uint8)

# Evluation Metrics

In [59]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [55]:
accuracy = accuracy_score(y_test, y_pred)

In [58]:
accuracy

0.9192825112107623

In [56]:
cm = confusion_matrix(y_test, y_pred)

In [61]:
cm

array([[954,   1],
       [ 89,  71]], dtype=int64)

In [60]:
cr  = classification_report(y_test, y_pred)

In [62]:
cr

'              precision    recall  f1-score   support\n\n           0       0.91      1.00      0.95       955\n           1       0.99      0.44      0.61       160\n\n    accuracy                           0.92      1115\n   macro avg       0.95      0.72      0.78      1115\nweighted avg       0.92      0.92      0.91      1115\n'

# Cross Validation

In [51]:
from sklearn.model_selection import cross_val_score

In [65]:
cv_Scores = cross_val_score(spem_detect, X_train, y_train, cv= 10, scoring = "accuracy")

In [66]:
cv_Scores

array([0.9058296 , 0.91479821, 0.91704036, 0.91704036, 0.93721973,
       0.91255605, 0.92152466, 0.92134831, 0.90786517, 0.92359551])